// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v7.35.1
// source: src/common/internal-protobuf/global-property.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";

/** Properties of the last successful mediator connection. */
export interface LastMediatorConnection {
  date?: Long | undefined;
}

export interface ApplicationState {
  /** default: false */
  unrecoverableStateDetected?: boolean | undefined;
}

function createBaseLastMediatorConnection(): LastMediatorConnection {
  return { date: undefined };
}

export const LastMediatorConnection: MessageFns<LastMediatorConnection> = {
  encode(message: LastMediatorConnection, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.date !== undefined) {
      writer.uint32(8).uint64(message.date.toString());
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LastMediatorConnection {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLastMediatorConnection();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.date = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseApplicationState(): ApplicationState {
  return { unrecoverableStateDetected: undefined };
}

export const ApplicationState: MessageFns<ApplicationState> = {
  encode(message: ApplicationState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.unrecoverableStateDetected !== undefined) {
      writer.uint32(8).bool(message.unrecoverableStateDetected);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApplicationState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApplicationState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.unrecoverableStateDetected = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
