// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v7.35.1
// source: src/common/internal-protobuf/key-storage-file.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";

/**
 * Argon2id parameters.
 *
 * We currently recommend to use the following minimum parameter values:
 *
 * - Memory: At least 128 MiB
 * - Iterations: At least 3
 *
 * Ideally, the parameters are tuned for the system in the following way:
 *
 * 1. Choose a maximum `time` the algorithm should run. For our use case, ~2s at application startup
 *    are acceptable.
 * 2. Figure out the an appropriate `memory` value based on weak target hardware.
 * 3. Run Argon2id and increase the number of `memory` and `iterations` until the targeted `time` is
 *    roughly matched.
 */
export interface Argon2idParameters {
  version: Argon2idParameters_Argon2Version;
  /** Random salt (≥ 16 bytes, recommended to be 16 bytes) */
  salt: Uint8Array;
  /** Memory usage in bytes (≥ 128 MiB) */
  memoryBytes: number;
  /** Number of iterations (≥ 3) */
  iterations: number;
  /** Amount of parallelism (≥ 1, recommended to be 1) */
  parallelism: number;
}

/** Version of Argon2 */
export const Argon2idParameters_Argon2Version = { VERSION_1_3: 0, UNRECOGNIZED: -1 } as const;

export type Argon2idParameters_Argon2Version =
  typeof Argon2idParameters_Argon2Version[keyof typeof Argon2idParameters_Argon2Version];

export namespace Argon2idParameters_Argon2Version {
  export type VERSION_1_3 = typeof Argon2idParameters_Argon2Version.VERSION_1_3;
  export type UNRECOGNIZED = typeof Argon2idParameters_Argon2Version.UNRECOGNIZED;
}

export interface RemoteSecretProtected {
  /** Associated remote secret authentication token */
  remoteSecretAuthenticationToken: Uint8Array;
  /** Associated remote secret hash */
  remoteSecretHash: Uint8Array;
  /**
   * Cached URL for fetching the remote secret, only relevant for OnPrem.
   *
   * Empty string if not OnPrem.
   *
   * If OnPrem, this endpoint URL must be updated to a non-empty string
   * whenever the respective URL in the OPPF file is changed.
   */
  onPremCachedRemoteSecretEndpointUrl: string;
  /**
   * Encapsulated compatible, version-prefixed inner key storage, encrypted
   * and encoded in the following way:
   *
   * 1. Let `RS` be the remote secret.
   * 2. Let `RSSK` be the result of
   *    `BLAKE2b(key=RS, salt='rssk-d', personal='3ma-rs')`.
   * 3. Let `inner` be the plaintext `Inner`, encoded to bytes.
   * 4. Let `nonce` be a random nonce.
   * 5. Let `encrypted-inner` be the result of encrypting `inner` by
   *    `XSalsa20-Poly1305(key=RSSK, nonce)`.
   * 6. Set this field to `nonce || encrypted-inner` (i.e. an
   *    `extra.crypto.encrypted-data-with-nonce-ahead` struct).
   */
  encryptedInner: Uint8Array;
}

export interface DeviceIds {
  /** The device ID used towards the mediator server */
  d2mDeviceId: Long;
  /** The device ID used towards the chat server */
  cspDeviceId: Long;
}

export interface IdentityData {
  /** The Threema ID string */
  identity: string;
  /** The permanent client key associated to the Threema ID (32 bytes) */
  ck: Uint8Array;
  /** The server group associated to the Threema ID (1 byte) */
  serverGroup: string;
}

export interface OnPremConfig {
  oppfUrl: string;
  lastUpdated: Long;
  oppfCachedConfig: string;
}

export interface ThreemaWorkCredentials {
  username: string;
  password: string;
}

export interface InnerKeyStorage {
}

export const InnerKeyStorage_Version = {
  /** V1_0 - Initial version */
  V1_0: 0,
  /**
   * V1_1 - Changes to the previous version:
   *
   * - Add string-based server group to replace numeric server group
   */
  V1_1: 1,
  /**
   * V2_0 - Changes to the previous version:
   *
   * - Externalise version number
   * - Removed deprecated server group
   * - Made device cookie mandatory
   */
  V2_0: 2,
  /**
   * V3_0 - Changes to the previous version:
   *
   * - Remove on_prem_config and work_credentials.
   */
  V3_0: 3,
  UNRECOGNIZED: -1,
} as const;

export type InnerKeyStorage_Version = typeof InnerKeyStorage_Version[keyof typeof InnerKeyStorage_Version];

export namespace InnerKeyStorage_Version {
  export type V1_0 = typeof InnerKeyStorage_Version.V1_0;
  export type V1_1 = typeof InnerKeyStorage_Version.V1_1;
  export type V2_0 = typeof InnerKeyStorage_Version.V2_0;
  export type V3_0 = typeof InnerKeyStorage_Version.V3_0;
  export type UNRECOGNIZED = typeof InnerKeyStorage_Version.UNRECOGNIZED;
}

export interface IntermediateKeyStorage {
}

export const IntermediateKeyStorage_Version = {
  /** V1_0 - Initial version */
  V1_0: 0,
  /**
   * V1_1 - Changes to the previous version:
   *
   * - Add on_prem_config and work_credentials from inner key storage.
   */
  V1_1: 1,
  UNRECOGNIZED: -1,
} as const;

export type IntermediateKeyStorage_Version =
  typeof IntermediateKeyStorage_Version[keyof typeof IntermediateKeyStorage_Version];

export namespace IntermediateKeyStorage_Version {
  export type V1_0 = typeof IntermediateKeyStorage_Version.V1_0;
  export type V1_1 = typeof IntermediateKeyStorage_Version.V1_1;
  export type UNRECOGNIZED = typeof IntermediateKeyStorage_Version.UNRECOGNIZED;
}

export interface OuterKeyStorage {
}

export const OuterKeyStorage_Version = {
  /** V1_0 - Initial version */
  V1_0: 0,
  /**
   * V2_0 - Changes to the previous version:
   *
   * - Externalise version number
   *
   * NOTE: This is a non-backward compatible change so it resulted in a new key storage file being
   * written.
   */
  V2_0: 1,
  UNRECOGNIZED: -1,
} as const;

export type OuterKeyStorage_Version = typeof OuterKeyStorage_Version[keyof typeof OuterKeyStorage_Version];

export namespace OuterKeyStorage_Version {
  export type V1_0 = typeof OuterKeyStorage_Version.V1_0;
  export type V2_0 = typeof OuterKeyStorage_Version.V2_0;
  export type UNRECOGNIZED = typeof OuterKeyStorage_Version.UNRECOGNIZED;
}

export interface InnerKeyStorageV1 {
  /**
   * The key storage schema version. Used for being able to migrate the storage
   * format.
   */
  schemaVersion: number;
  /** Data associated to the Threema ID */
  identityData:
    | IdentityData
    | undefined;
  /** The device group key (32 bytes) */
  dgk: Uint8Array;
  /** The SQLCipher database encryption key (32 bytes) */
  databaseKey: Uint8Array;
  /** Device IDs */
  deviceIds:
    | DeviceIds
    | undefined;
  /** The device cookie (16 bytes) */
  deviceCookie?:
    | Uint8Array
    | undefined;
  /** Threema Work Credentials (if any) */
  workCredentials:
    | ThreemaWorkCredentials
    | undefined;
  /** Threema OnPrem Config (if any) */
  onPremConfig: OnPremConfig | undefined;
}

/**
 * Inner key storage V2, encoded in the following way:
 *
 * 1. Let `data` be the result of encoding this key storage to bytes.
 * 2. Let `version` be the selected `InnerKeyStorage_Version.V2_X` version.
 * 3. Return `u16-le(version) || data`.
 */
export interface InnerKeyStorageV2 {
  /** Data associated to the Threema ID */
  identityData:
    | IdentityData
    | undefined;
  /** Threema Work Credentials (if any) */
  workCredentials:
    | ThreemaWorkCredentials
    | undefined;
  /** The device group key (32 bytes) */
  dgk: Uint8Array;
  /** The SQLCipher database encryption key (32 bytes) */
  databaseKey: Uint8Array;
  /** Device IDs */
  deviceIds:
    | DeviceIds
    | undefined;
  /** The device cookie (16 bytes) */
  deviceCookie: Uint8Array;
  /** Threema OnPrem config (if any) */
  onPremConfig: OnPremConfig | undefined;
}

/**
 * Inner key storage V3, encoded in the following way:
 *
 * 1. Let `data` be the result of encoding this key storage to bytes.
 * 2. Let `version` be the selected `InnerKeyStorage_Version.V3_X` version.
 * 3. Return `u16-le(version) || data`.
 */
export interface InnerKeyStorageV3 {
  /** Data associated to the Threema ID */
  identityData:
    | IdentityData
    | undefined;
  /** The device group key (32 bytes) */
  dgk: Uint8Array;
  /** The SQLCipher database encryption key (32 bytes) */
  databaseKey: Uint8Array;
  /** Device IDs */
  deviceIds:
    | DeviceIds
    | undefined;
  /** The device cookie (16 bytes) */
  deviceCookie: Uint8Array;
}

/**
 * Intermediate key storage V1, encoded in the following way:
 *
 * 1. Let `data` be the result of encoding this key storage to bytes.
 * 2. Let `version` be the selected `IntermediateKeyStorage_Version.V1_X` version.
 * 3. Return `u16-le(version) || data`.
 */
export interface IntermediateKeyStorageV1 {
  inner?:
    | //
    /**
     * A compatible, version-prefixed inner key storage without any further
     * protection
     */
    { $case: "plaintextInner"; plaintextInner: Uint8Array }
    | //
    /** Inner key storage protected by the Remote Secret protocol */
    { $case: "remoteSecretProtectedInner"; remoteSecretProtectedInner: RemoteSecretProtected }
    | undefined;
}

/**
 * Intermediate key storage V1_1, encoded in the following way:
 *
 * 1. Let `data` be the result of encoding this key storage to bytes.
 * 2. Let `version` be the selected `IntermediateKeyStorage_Version.V1_X` version.
 * 3. Return `u16-le(version) || data`.
 */
export interface IntermediateKeyStorageV11 {
  inner?:
    | //
    /**
     * A compatible, version-prefixed inner key storage without any further
     * protection
     */
    { $case: "plaintextInner"; plaintextInner: Uint8Array }
    | //
    /** Inner key storage protected by the Remote Secret protocol */
    { $case: "remoteSecretProtectedInner"; remoteSecretProtectedInner: RemoteSecretProtected }
    | undefined;
  /** Threema Work Credentials (if any) */
  workCredentials:
    | ThreemaWorkCredentials
    | undefined;
  /** Threema OnPrem config (if any) */
  onPremConfig: OnPremConfig | undefined;
}

export interface OuterKeyStorageV1 {
  /**
   * The key storage schema version. Used for being able to migrate the storage
   * format.
   */
  schemaVersion: number;
  /**
   * Contains the key storage (`KeyStorage`), encrypted and encoded in the
   * following way:
   *
   * 1. Let `plain_storage` be the plaintext `KeyStorage`, encoded to bytes.
   * 2. Let `sk` be a 32 byte secret key derived by running the chosen KDF
   *    with its parameters and the user-provided passphrase.
   * 3. Let `nonce` be a random nonce.
   * 4. Let `encrypted_storage` be the result of an NaCl box encryption with
   *    `sk` as the secret key, `nonce` as the nonce and `plain_storage` as
   *    data.
   * 5. Set `encrypted_key_storage` to `nonce || encrypted_storage` (i.e. a
   *    `extra.crypto.encrypted-data-with-nonce-ahead` struct).
   */
  encryptedKeyStorage: Uint8Array;
  /** The KDF and associated parameters */
  kdfParameters?: { $case: "argon2id"; argon2id: Argon2idParameters } | undefined;
}

/**
 * Outer key storage V2, encoded in the following way:
 *
 * 1. Let `data` be the result of encoding this key storage to bytes.
 * 2. Let `version` be the selected `OuterVersion.V2_X` version.
 * 3. Return `u16-le(version) || data`.
 */
export interface OuterKeyStorageV2 {
  /**
   * Encapsulated compatible, version-prefixed intermediate key storage,
   * encrypted and encoded in the following way:
   *
   * 1. Let `SK` be a 32 byte secret key derived by running the chosen KDF
   *    with its parameters and the user-provided passphrase.
   * 2. Let `nonce` be a random nonce.
   * 3. Let `intermediate` be a compatible, version-prefixed intermediate key
   *    storage encoded to bytes.
   * 4. Let `encrypted-intermediate` be the result of encrypting `intermediate`
   *    by `XSalsa20-Poly1305(key=SK, nonce)`.
   * 5. Set this field to `nonce || encrypted-intermediate` (i.e. an
   *    `extra.crypto.encrypted-data-with-nonce-ahead` struct).
   */
  encryptedIntermediate: Uint8Array;
  /** The KDF and associated parameters */
  kdfParameters?: { $case: "argon2id"; argon2id: Argon2idParameters } | undefined;
}

function createBaseArgon2idParameters(): Argon2idParameters {
  return { version: 0, salt: new Uint8Array(0), memoryBytes: 0, iterations: 0, parallelism: 0 };
}

export const Argon2idParameters: MessageFns<Argon2idParameters> = {
  encode(message: Argon2idParameters, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.version !== 0) {
      writer.uint32(8).int32(message.version);
    }
    if (message.salt.length !== 0) {
      writer.uint32(18).bytes(message.salt);
    }
    if (message.memoryBytes !== 0) {
      writer.uint32(24).uint32(message.memoryBytes);
    }
    if (message.iterations !== 0) {
      writer.uint32(32).uint32(message.iterations);
    }
    if (message.parallelism !== 0) {
      writer.uint32(40).uint32(message.parallelism);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Argon2idParameters {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArgon2idParameters();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.version = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.salt = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.memoryBytes = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.iterations = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.parallelism = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseRemoteSecretProtected(): RemoteSecretProtected {
  return {
    remoteSecretAuthenticationToken: new Uint8Array(0),
    remoteSecretHash: new Uint8Array(0),
    onPremCachedRemoteSecretEndpointUrl: "",
    encryptedInner: new Uint8Array(0),
  };
}

export const RemoteSecretProtected: MessageFns<RemoteSecretProtected> = {
  encode(message: RemoteSecretProtected, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.remoteSecretAuthenticationToken.length !== 0) {
      writer.uint32(10).bytes(message.remoteSecretAuthenticationToken);
    }
    if (message.remoteSecretHash.length !== 0) {
      writer.uint32(18).bytes(message.remoteSecretHash);
    }
    if (message.onPremCachedRemoteSecretEndpointUrl !== "") {
      writer.uint32(26).string(message.onPremCachedRemoteSecretEndpointUrl);
    }
    if (message.encryptedInner.length !== 0) {
      writer.uint32(34).bytes(message.encryptedInner);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemoteSecretProtected {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoteSecretProtected();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.remoteSecretAuthenticationToken = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.remoteSecretHash = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.onPremCachedRemoteSecretEndpointUrl = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.encryptedInner = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDeviceIds(): DeviceIds {
  return { d2mDeviceId: Long.UZERO, cspDeviceId: Long.UZERO };
}

export const DeviceIds: MessageFns<DeviceIds> = {
  encode(message: DeviceIds, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (!message.d2mDeviceId.equals(Long.UZERO)) {
      writer.uint32(8).uint64(message.d2mDeviceId.toString());
    }
    if (!message.cspDeviceId.equals(Long.UZERO)) {
      writer.uint32(16).uint64(message.cspDeviceId.toString());
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeviceIds {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeviceIds();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.d2mDeviceId = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.cspDeviceId = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseIdentityData(): IdentityData {
  return { identity: "", ck: new Uint8Array(0), serverGroup: "" };
}

export const IdentityData: MessageFns<IdentityData> = {
  encode(message: IdentityData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.identity !== "") {
      writer.uint32(10).string(message.identity);
    }
    if (message.ck.length !== 0) {
      writer.uint32(18).bytes(message.ck);
    }
    if (message.serverGroup !== "") {
      writer.uint32(34).string(message.serverGroup);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IdentityData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIdentityData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.identity = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ck = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.serverGroup = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseOnPremConfig(): OnPremConfig {
  return { oppfUrl: "", lastUpdated: Long.UZERO, oppfCachedConfig: "" };
}

export const OnPremConfig: MessageFns<OnPremConfig> = {
  encode(message: OnPremConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.oppfUrl !== "") {
      writer.uint32(10).string(message.oppfUrl);
    }
    if (!message.lastUpdated.equals(Long.UZERO)) {
      writer.uint32(16).uint64(message.lastUpdated.toString());
    }
    if (message.oppfCachedConfig !== "") {
      writer.uint32(26).string(message.oppfCachedConfig);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OnPremConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOnPremConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.oppfUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.lastUpdated = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.oppfCachedConfig = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseThreemaWorkCredentials(): ThreemaWorkCredentials {
  return { username: "", password: "" };
}

export const ThreemaWorkCredentials: MessageFns<ThreemaWorkCredentials> = {
  encode(message: ThreemaWorkCredentials, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ThreemaWorkCredentials {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseThreemaWorkCredentials();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseInnerKeyStorage(): InnerKeyStorage {
  return {};
}

export const InnerKeyStorage: MessageFns<InnerKeyStorage> = {
  encode(_: InnerKeyStorage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InnerKeyStorage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInnerKeyStorage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseIntermediateKeyStorage(): IntermediateKeyStorage {
  return {};
}

export const IntermediateKeyStorage: MessageFns<IntermediateKeyStorage> = {
  encode(_: IntermediateKeyStorage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IntermediateKeyStorage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIntermediateKeyStorage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseOuterKeyStorage(): OuterKeyStorage {
  return {};
}

export const OuterKeyStorage: MessageFns<OuterKeyStorage> = {
  encode(_: OuterKeyStorage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OuterKeyStorage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOuterKeyStorage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseInnerKeyStorageV1(): InnerKeyStorageV1 {
  return {
    schemaVersion: 0,
    identityData: undefined,
    dgk: new Uint8Array(0),
    databaseKey: new Uint8Array(0),
    deviceIds: undefined,
    deviceCookie: undefined,
    workCredentials: undefined,
    onPremConfig: undefined,
  };
}

export const InnerKeyStorageV1: MessageFns<InnerKeyStorageV1> = {
  encode(message: InnerKeyStorageV1, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.schemaVersion !== 0) {
      writer.uint32(40).uint32(message.schemaVersion);
    }
    if (message.identityData !== undefined) {
      IdentityData.encode(message.identityData, writer.uint32(10).fork()).join();
    }
    if (message.dgk.length !== 0) {
      writer.uint32(18).bytes(message.dgk);
    }
    if (message.databaseKey.length !== 0) {
      writer.uint32(26).bytes(message.databaseKey);
    }
    if (message.deviceIds !== undefined) {
      DeviceIds.encode(message.deviceIds, writer.uint32(34).fork()).join();
    }
    if (message.deviceCookie !== undefined) {
      writer.uint32(66).bytes(message.deviceCookie);
    }
    if (message.workCredentials !== undefined) {
      ThreemaWorkCredentials.encode(message.workCredentials, writer.uint32(50).fork()).join();
    }
    if (message.onPremConfig !== undefined) {
      OnPremConfig.encode(message.onPremConfig, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InnerKeyStorageV1 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInnerKeyStorageV1();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.schemaVersion = reader.uint32();
          continue;
        }
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.identityData = IdentityData.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.dgk = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.databaseKey = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.deviceIds = DeviceIds.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.deviceCookie = reader.bytes();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.workCredentials = ThreemaWorkCredentials.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.onPremConfig = OnPremConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseInnerKeyStorageV2(): InnerKeyStorageV2 {
  return {
    identityData: undefined,
    workCredentials: undefined,
    dgk: new Uint8Array(0),
    databaseKey: new Uint8Array(0),
    deviceIds: undefined,
    deviceCookie: new Uint8Array(0),
    onPremConfig: undefined,
  };
}

export const InnerKeyStorageV2: MessageFns<InnerKeyStorageV2> = {
  encode(message: InnerKeyStorageV2, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.identityData !== undefined) {
      IdentityData.encode(message.identityData, writer.uint32(10).fork()).join();
    }
    if (message.workCredentials !== undefined) {
      ThreemaWorkCredentials.encode(message.workCredentials, writer.uint32(18).fork()).join();
    }
    if (message.dgk.length !== 0) {
      writer.uint32(26).bytes(message.dgk);
    }
    if (message.databaseKey.length !== 0) {
      writer.uint32(34).bytes(message.databaseKey);
    }
    if (message.deviceIds !== undefined) {
      DeviceIds.encode(message.deviceIds, writer.uint32(42).fork()).join();
    }
    if (message.deviceCookie.length !== 0) {
      writer.uint32(50).bytes(message.deviceCookie);
    }
    if (message.onPremConfig !== undefined) {
      OnPremConfig.encode(message.onPremConfig, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InnerKeyStorageV2 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInnerKeyStorageV2();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.identityData = IdentityData.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.workCredentials = ThreemaWorkCredentials.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.dgk = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.databaseKey = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.deviceIds = DeviceIds.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.deviceCookie = reader.bytes();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.onPremConfig = OnPremConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseInnerKeyStorageV3(): InnerKeyStorageV3 {
  return {
    identityData: undefined,
    dgk: new Uint8Array(0),
    databaseKey: new Uint8Array(0),
    deviceIds: undefined,
    deviceCookie: new Uint8Array(0),
  };
}

export const InnerKeyStorageV3: MessageFns<InnerKeyStorageV3> = {
  encode(message: InnerKeyStorageV3, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.identityData !== undefined) {
      IdentityData.encode(message.identityData, writer.uint32(10).fork()).join();
    }
    if (message.dgk.length !== 0) {
      writer.uint32(18).bytes(message.dgk);
    }
    if (message.databaseKey.length !== 0) {
      writer.uint32(26).bytes(message.databaseKey);
    }
    if (message.deviceIds !== undefined) {
      DeviceIds.encode(message.deviceIds, writer.uint32(34).fork()).join();
    }
    if (message.deviceCookie.length !== 0) {
      writer.uint32(42).bytes(message.deviceCookie);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InnerKeyStorageV3 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInnerKeyStorageV3();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.identityData = IdentityData.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.dgk = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.databaseKey = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.deviceIds = DeviceIds.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.deviceCookie = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseIntermediateKeyStorageV1(): IntermediateKeyStorageV1 {
  return { inner: undefined };
}

export const IntermediateKeyStorageV1: MessageFns<IntermediateKeyStorageV1> = {
  encode(message: IntermediateKeyStorageV1, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    switch (message.inner?.$case) {
      case "plaintextInner":
        writer.uint32(10).bytes(message.inner.plaintextInner);
        break;
      case "remoteSecretProtectedInner":
        RemoteSecretProtected.encode(message.inner.remoteSecretProtectedInner, writer.uint32(18).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IntermediateKeyStorageV1 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIntermediateKeyStorageV1();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.inner = { $case: "plaintextInner", plaintextInner: reader.bytes() };
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.inner = {
            $case: "remoteSecretProtectedInner",
            remoteSecretProtectedInner: RemoteSecretProtected.decode(reader, reader.uint32()),
          };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseIntermediateKeyStorageV11(): IntermediateKeyStorageV11 {
  return { inner: undefined, workCredentials: undefined, onPremConfig: undefined };
}

export const IntermediateKeyStorageV11: MessageFns<IntermediateKeyStorageV11> = {
  encode(message: IntermediateKeyStorageV11, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    switch (message.inner?.$case) {
      case "plaintextInner":
        writer.uint32(10).bytes(message.inner.plaintextInner);
        break;
      case "remoteSecretProtectedInner":
        RemoteSecretProtected.encode(message.inner.remoteSecretProtectedInner, writer.uint32(18).fork()).join();
        break;
    }
    if (message.workCredentials !== undefined) {
      ThreemaWorkCredentials.encode(message.workCredentials, writer.uint32(26).fork()).join();
    }
    if (message.onPremConfig !== undefined) {
      OnPremConfig.encode(message.onPremConfig, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IntermediateKeyStorageV11 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIntermediateKeyStorageV11();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.inner = { $case: "plaintextInner", plaintextInner: reader.bytes() };
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.inner = {
            $case: "remoteSecretProtectedInner",
            remoteSecretProtectedInner: RemoteSecretProtected.decode(reader, reader.uint32()),
          };
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.workCredentials = ThreemaWorkCredentials.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.onPremConfig = OnPremConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseOuterKeyStorageV1(): OuterKeyStorageV1 {
  return { schemaVersion: 0, encryptedKeyStorage: new Uint8Array(0), kdfParameters: undefined };
}

export const OuterKeyStorageV1: MessageFns<OuterKeyStorageV1> = {
  encode(message: OuterKeyStorageV1, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.schemaVersion !== 0) {
      writer.uint32(24).uint32(message.schemaVersion);
    }
    if (message.encryptedKeyStorage.length !== 0) {
      writer.uint32(10).bytes(message.encryptedKeyStorage);
    }
    switch (message.kdfParameters?.$case) {
      case "argon2id":
        Argon2idParameters.encode(message.kdfParameters.argon2id, writer.uint32(18).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OuterKeyStorageV1 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOuterKeyStorageV1();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.schemaVersion = reader.uint32();
          continue;
        }
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.encryptedKeyStorage = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.kdfParameters = { $case: "argon2id", argon2id: Argon2idParameters.decode(reader, reader.uint32()) };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseOuterKeyStorageV2(): OuterKeyStorageV2 {
  return { encryptedIntermediate: new Uint8Array(0), kdfParameters: undefined };
}

export const OuterKeyStorageV2: MessageFns<OuterKeyStorageV2> = {
  encode(message: OuterKeyStorageV2, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.encryptedIntermediate.length !== 0) {
      writer.uint32(10).bytes(message.encryptedIntermediate);
    }
    switch (message.kdfParameters?.$case) {
      case "argon2id":
        Argon2idParameters.encode(message.kdfParameters.argon2id, writer.uint32(18).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OuterKeyStorageV2 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOuterKeyStorageV2();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.encryptedIntermediate = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.kdfParameters = { $case: "argon2id", argon2id: Argon2idParameters.decode(reader, reader.uint32()) };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
