// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v7.35.1
// source: src/common/internal-protobuf/persistent-protocol-state.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

/**
 * ## Persistent Protocol State
 *
 * The persistent protocol state which is persisted over restarts.
 */

export interface UserProfileState {
  /** Identity of the receiver */
  receiverIdentity: string;
  /** BlobId of the profile picture */
  blobId?: Uint8Array | undefined;
}

function createBaseUserProfileState(): UserProfileState {
  return { receiverIdentity: "", blobId: undefined };
}

export const UserProfileState: MessageFns<UserProfileState> = {
  encode(message: UserProfileState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.receiverIdentity !== "") {
      writer.uint32(10).string(message.receiverIdentity);
    }
    if (message.blobId !== undefined) {
      writer.uint32(18).bytes(message.blobId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserProfileState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserProfileState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.receiverIdentity = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.blobId = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
