// WARNING: This file has been generated by safe-enums. Do not modify it!
// @ts-nocheck

import type {u53} from '~/common/types';
export namespace MessageDirection {
    export const INBOUND = 0;
    export type INBOUND = typeof INBOUND;
    export const OUTBOUND = 1;
    export type OUTBOUND = typeof OUTBOUND;
}
/**
 * An enum whose members are numbered implicitly, requesting conversion helpers.
 *
 * @generate convert
 */
export type MessageDirection = (typeof MessageDirection)[keyof typeof MessageDirection];
export namespace MessageDirectionUtils {
    export const ALL: ReadonlySet<MessageDirection> = new Set([
        MessageDirection.INBOUND,
        MessageDirection.OUTBOUND,
    ] as const);
    export function fromNumber(value: u53, fallback?: MessageDirection): MessageDirection {
        if ((ALL as ReadonlySet<u53>).has(value)) {
            return value as MessageDirection;
        }
        if (fallback !== undefined) {
            return fallback;
        }
        throw new Error(`${value} is not a valid MessageDirection`);
    }
    export function containsNumber(value: u53): value is MessageDirection {
        return (ALL as ReadonlySet<u53>).has(value);
    }
    export function contains(value: unknown): value is MessageDirection {
        return typeof value === 'number' && (ALL as ReadonlySet<u53>).has(value);
    }
}

// WARNING: This file has been generated by safe-enums. Do not modify it!
// vim: set readonly :
