// WARNING: This file has been generated by safe-enums. Do not modify it!
// @ts-nocheck

export namespace MessageDirection {
    export const INBOUND = 0;
    export type INBOUND = typeof INBOUND;
    export const OUTBOUND = 1;
    export type OUTBOUND = typeof OUTBOUND;
}
/**
 * An enum in a schema that leads with TypeScript directives, and has no imports to separate them
 * from the enum. The directives are copied to the top of the generated module, and are not repeated
 * as the documentation comment of the enum.
 */
export type MessageDirection = (typeof MessageDirection)[keyof typeof MessageDirection];

// WARNING: This file has been generated by safe-enums. Do not modify it!
// vim: set readonly :
