// WARNING: This file has been generated by safe-enums. Do not modify it!
// @ts-nocheck

import type {Logger} from '~/common/logging';
import type {u53} from '~/common/types';
import type {MonotonicEnumStore, StoreDebug} from '~/common/utils/store';
export namespace ConnectionState {
    export const DISCONNECTED = 0;
    /** Not connected. */
    export type DISCONNECTED = typeof DISCONNECTED;
    export const CONNECTING = 1;
    /** Connection is being established. */
    export type CONNECTING = typeof CONNECTING;
    export const CONNECTED = 16;
    /** Connection has been established. */
    export type CONNECTED = typeof CONNECTED;
}
/**
 * A numeric enum requesting all available utilities.
 *
 * @generate convert name store
 */
export type ConnectionState = (typeof ConnectionState)[keyof typeof ConnectionState];
export namespace ConnectionStateUtils {
    export const ALL: ReadonlySet<ConnectionState> = new Set([
        ConnectionState.DISCONNECTED,
        ConnectionState.CONNECTING,
        ConnectionState.CONNECTED,
    ] as const);
    export function fromNumber(value: u53, fallback?: ConnectionState): ConnectionState {
        if ((ALL as ReadonlySet<u53>).has(value)) {
            return value as ConnectionState;
        }
        if (fallback !== undefined) {
            return fallback;
        }
        throw new Error(`${value} is not a valid ConnectionState`);
    }
    export function containsNumber(value: u53): value is ConnectionState {
        return (ALL as ReadonlySet<u53>).has(value);
    }
    export function contains(value: unknown): value is ConnectionState {
        return typeof value === 'number' && (ALL as ReadonlySet<u53>).has(value);
    }
    export const NAME_OF = {
        [ConnectionState.DISCONNECTED]: 'DISCONNECTED',
        [ConnectionState.CONNECTING]: 'CONNECTING',
        [ConnectionState.CONNECTED]: 'CONNECTED',
    } as const;
    export function nameOf<T extends u53>(value: T): string | undefined {
        return (NAME_OF as Record<u53, string | undefined>)[value];
    }
    export function createStore<S extends MonotonicEnumStore<ConnectionState>>(
        constructor: new (
            initial: ConnectionState,
            activator?: undefined,
            debug?: StoreDebug<ConnectionState>,
        ) => S,
        initial: ConnectionState,
        debug?: {
            log: Logger;
            tag: string;
        },
    ): S {
        return new constructor(
            initial,
            undefined,
            debug === undefined
                ? undefined
                : {
                      log: debug.log,
                      tag: debug.tag,
                      representation: (name): string => NAME_OF[name],
                  },
        );
    }
}

// WARNING: This file has been generated by safe-enums. Do not modify it!
// vim: set readonly :
