// WARNING: This file has been generated by safe-enums. Do not modify it!

export namespace ImageRenderingType {
    export const REGULAR = 'regular';
    export type REGULAR = typeof REGULAR;
    export const STICKER = 'sticker';
    export type STICKER = typeof STICKER;
}
/**
 * A string enum requesting conversion helpers.
 *
 * @generate convert
 */
export type ImageRenderingType = (typeof ImageRenderingType)[keyof typeof ImageRenderingType];
export namespace ImageRenderingTypeUtils {
    export const ALL: ReadonlySet<ImageRenderingType> = new Set([
        ImageRenderingType.REGULAR,
        ImageRenderingType.STICKER,
    ] as const);
    export function fromString(value: string, fallback?: ImageRenderingType): ImageRenderingType {
        if ((ALL as ReadonlySet<string>).has(value)) {
            return value as ImageRenderingType;
        }
        if (fallback !== undefined) {
            return fallback;
        }
        throw new Error(`${value} is not a valid ImageRenderingType`);
    }
    export function containsString(value: string): value is ImageRenderingType {
        return (ALL as ReadonlySet<string>).has(value);
    }
    export function contains(value: unknown): value is ImageRenderingType {
        return typeof value === 'string' && (ALL as ReadonlySet<string>).has(value);
    }
}
export namespace ActivityState {
    export const ACTIVE = 0;
    export type ACTIVE = typeof ACTIVE;
    export const INACTIVE = 1;
    export type INACTIVE = typeof INACTIVE;
}
/**
 * A numeric enum without utilities, whose members have no initialisers.
 */
export type ActivityState = (typeof ActivityState)[keyof typeof ActivityState];

// WARNING: This file has been generated by safe-enums. Do not modify it!
// vim: set readonly :
