// WARNING: This file has been generated by safe-enums. Do not modify it!
// @ts-nocheck

import type {u53} from '@threema/ts-utils/integer/u53';
export namespace CspPayloadType {
    export const ECHO_REQUEST = 0;
    export type ECHO_REQUEST = typeof ECHO_REQUEST;
    export const ECHO_RESPONSE = 128;
    export type ECHO_RESPONSE = typeof ECHO_RESPONSE;
}
/**
 * A numeric enum whose utilities reference `u53`, but not `Logger`. The `Logger` import is therefore
 * dropped from the generated module.
 *
 * @generate convert
 */
export type CspPayloadType = (typeof CspPayloadType)[keyof typeof CspPayloadType];
export namespace CspPayloadTypeUtils {
    export const ALL: ReadonlySet<CspPayloadType> = new Set([
        CspPayloadType.ECHO_REQUEST,
        CspPayloadType.ECHO_RESPONSE,
    ] as const);
    export function fromNumber(value: u53, fallback?: CspPayloadType): CspPayloadType {
        if ((ALL as ReadonlySet<u53>).has(value)) {
            return value as CspPayloadType;
        }
        if (fallback !== undefined) {
            return fallback;
        }
        throw new Error(`${value} is not a valid CspPayloadType`);
    }
    export function containsNumber(value: u53): value is CspPayloadType {
        return (ALL as ReadonlySet<u53>).has(value);
    }
    export function contains(value: unknown): value is CspPayloadType {
        return typeof value === 'number' && (ALL as ReadonlySet<u53>).has(value);
    }
}

// WARNING: This file has been generated by safe-enums. Do not modify it!
// vim: set readonly :
