// WARNING: This file has been generated by safe-enums. Do not modify it!

import type {u53} from '@threema/ts-utils/integer/u53';
export namespace NonceScope {
    export const CSP = 0;
    export type CSP = typeof CSP;
    export const D2D = 1;
    export type D2D = typeof D2D;
}
/**
 * All enums whose values are defined by the Threema protocol or appear on the wire are declared in
 * this file.
 *
 * Use `pnpm run generate:protocol:safe-enums` to generate safer enum variants from them, which are
 * then imported from `@threema/protocol/enum`.
 *
 * See `packages/safe-enums/README.md` for how to write a schema and for which package owns which
 * enum.
 */
/**
 * Nonce scopes. Defines in which context a nonce must be unique.
 *
 * @generate convert
 */
export type NonceScope = (typeof NonceScope)[keyof typeof NonceScope];
export namespace NonceScopeUtils {
    export const ALL: ReadonlySet<NonceScope> = new Set([NonceScope.CSP, NonceScope.D2D] as const);
    export function fromNumber(value: u53, fallback?: NonceScope): NonceScope {
        if ((ALL as ReadonlySet<u53>).has(value)) {
            return value as NonceScope;
        }
        if (fallback !== undefined) {
            return fallback;
        }
        throw new Error(`${value} is not a valid NonceScope`);
    }
    export function containsNumber(value: u53): value is NonceScope {
        return (ALL as ReadonlySet<u53>).has(value);
    }
    export function contains(value: unknown): value is NonceScope {
        return typeof value === 'number' && (ALL as ReadonlySet<u53>).has(value);
    }
}

// WARNING: This file has been generated by safe-enums. Do not modify it!
// vim: set readonly :
