// @ts-check

/**
 * Generate safe enum wrappers from a schema.
 *
 * Note: For editing this module, https://ts-ast-viewer.com/ is very handy.
 */
// Note: TypeScript must be imported as a default import, because named-export detection on that
// package is unreliable under Node's ESM loader.
import ts from 'typescript';

import {createSource, getLeadingComments} from './generator-utils.mjs';

const factory = ts.factory;

// Often-used keywords
const u53Keyword = factory.createTypeReferenceNode(factory.createIdentifier('u53'), undefined);
const stringKeyword = factory.createKeywordTypeNode(ts.SyntaxKind.StringKeyword);

/**
 * Comment marking the generated module as generated.
 */
const GENERATED_WARNING_COMMENT =
    '// WARNING: This file has been generated by safe-enums. Do not modify it!';

/**
 * Vim modeline, appended to the generated module.
 */
const VIM_MODELINE = '// vim: set readonly :';

/**
 * Prefix of a TypeScript directive comment, e.g. `// @ts-nocheck`.
 */
const TYPESCRIPT_DIRECTIVE_PREFIX = '// @ts-';

/**
 * Extract lines at the top of a schema containing TypeScript directives, e.g. `// @ts-nocheck`.
 *
 * Note: In the returned `schemaWithoutDirectives`, the line(s) containing directives are blanked
 * instead of removing them entirely, so that the line numbers of the returned schema still match
 * the input schema.
 *
 * @param {string} schema The source text of the schema.
 * @returns {[directives: string[], schemaWithoutDirectives: string]} the topmost lines containing
 *   TypeScript directives, as well as the cleaned schema.
 */
function extractTsDirectives(schema) {
    const lines = schema.split('\n');
    const directives = [];
    for (const line of lines) {
        if (!line.startsWith(TYPESCRIPT_DIRECTIVE_PREFIX)) {
            break;
        }
        directives.push(line);
    }
    const rest = lines.map((line, index) => (index < directives.length ? '' : line)).join('\n');
    return [directives, rest];
}

/**
 * A named binding of an import declaration in a schema.
 *
 * @typedef {object} ImportBinding
 * @property {string | undefined} propertyName The imported name, if it is aliased.
 * @property {string} name The local name the binding is available under.
 */

/**
 * An import declaration of a schema, to be copied into the generated module.
 *
 * @typedef {object} SchemaImport
 * @property {string} specifier The module specifier to import from.
 * @property {ImportBinding[]} bindings The named bindings of the import declaration.
 */

/**
 * An error in the schema, reported with the location of the offending statement.
 */
export class SchemaError extends Error {
    /**
     * Create an error reporting the position of `node` within the schema.
     *
     * @param {string} message The reason why the schema was rejected.
     * @param {ts.SourceFile} source The schema source file.
     * @param {ts.Node} node The offending node.
     */
    constructor(message, source, node) {
        const {line, character} = source.getLineAndCharacterOfPosition(node.getStart(source));
        super(`${source.fileName}:${line + 1}:${character + 1}: ${message}`);
        this.name = 'SchemaError';
    }
}

/**
 * Create the functions converting a raw value into an enum value, along with the set of all enum
 * members the conversion checks against.
 *
 * @param {string} name The name of the enum.
 * @param {readonly {identifier: string, initializer: ts.Expression}[]} members The enum members.
 * @param {string | undefined} initializerType The kind of initialiser the members use.
 * @returns {ts.Statement[]} the conversion functions and the set of all enum members.
 * @throws {Error} if the members use an initialiser kind that cannot be converted.
 */
function createEnumConversionAndConstantSet(name, members, initializerType) {
    let functionNameFrom;
    let functionNameContainsTyped;
    /** @type {ts.TypeNode} */
    let paramType;
    let paramTypeLiteral;
    switch (initializerType) {
        case 'number':
            functionNameFrom = 'fromNumber';
            functionNameContainsTyped = 'containsNumber';
            paramType = u53Keyword;
            paramTypeLiteral = 'number';
            break;
        case 'string':
            functionNameFrom = 'fromString';
            functionNameContainsTyped = 'containsString';
            paramType = stringKeyword;
            paramTypeLiteral = 'string';
            break;
        default:
            throw new Error(`Invalid initializer type: ${initializerType}`);
    }
    return [
        factory.createVariableStatement(
            [factory.createModifier(ts.SyntaxKind.ExportKeyword)],
            factory.createVariableDeclarationList(
                [
                    factory.createVariableDeclaration(
                        factory.createIdentifier('ALL'),
                        undefined,
                        factory.createTypeReferenceNode(factory.createIdentifier('ReadonlySet'), [
                            factory.createTypeReferenceNode(
                                factory.createIdentifier(name),
                                undefined,
                            ),
                        ]),
                        factory.createNewExpression(factory.createIdentifier('Set'), undefined, [
                            factory.createAsExpression(
                                factory.createArrayLiteralExpression(
                                    members.map((member) =>
                                        factory.createPropertyAccessExpression(
                                            factory.createIdentifier(name),
                                            factory.createIdentifier(member.identifier),
                                        ),
                                    ),
                                    true,
                                ),
                                factory.createTypeReferenceNode(
                                    factory.createIdentifier('const'),
                                    undefined,
                                ),
                            ),
                        ]),
                    ),
                ],
                ts.NodeFlags.Const,
            ),
        ),

        // Function: fromXxx
        factory.createFunctionDeclaration(
            [factory.createModifier(ts.SyntaxKind.ExportKeyword)],
            undefined,
            factory.createIdentifier(functionNameFrom),
            undefined,
            [
                factory.createParameterDeclaration(
                    undefined,
                    undefined,
                    factory.createIdentifier('value'),
                    undefined,
                    paramType,
                    undefined,
                ),
                factory.createParameterDeclaration(
                    undefined,
                    undefined,
                    factory.createIdentifier('fallback'),
                    factory.createToken(ts.SyntaxKind.QuestionToken),
                    factory.createTypeReferenceNode(factory.createIdentifier(name), undefined),
                    undefined,
                ),
            ],
            factory.createTypeReferenceNode(factory.createIdentifier(name), undefined),
            factory.createBlock(
                [
                    factory.createIfStatement(
                        factory.createCallExpression(
                            factory.createPropertyAccessExpression(
                                factory.createParenthesizedExpression(
                                    factory.createAsExpression(
                                        factory.createIdentifier('ALL'),
                                        factory.createTypeReferenceNode(
                                            factory.createIdentifier('ReadonlySet'),
                                            [paramType],
                                        ),
                                    ),
                                ),
                                factory.createIdentifier('has'),
                            ),
                            undefined,
                            [factory.createIdentifier('value')],
                        ),
                        factory.createBlock(
                            [
                                factory.createReturnStatement(
                                    factory.createAsExpression(
                                        factory.createIdentifier('value'),
                                        factory.createTypeReferenceNode(
                                            factory.createIdentifier(name),
                                            undefined,
                                        ),
                                    ),
                                ),
                            ],
                            true,
                        ),
                        undefined,
                    ),
                    factory.createIfStatement(
                        factory.createBinaryExpression(
                            factory.createIdentifier('fallback'),
                            factory.createToken(ts.SyntaxKind.ExclamationEqualsEqualsToken),
                            factory.createIdentifier('undefined'),
                        ),
                        factory.createBlock(
                            [factory.createReturnStatement(factory.createIdentifier('fallback'))],
                            true,
                        ),
                        undefined,
                    ),
                    factory.createThrowStatement(
                        factory.createNewExpression(factory.createIdentifier('Error'), undefined, [
                            factory.createTemplateExpression(factory.createTemplateHead('', ''), [
                                factory.createTemplateSpan(
                                    factory.createIdentifier('value'),
                                    factory.createTemplateTail(
                                        ` is not a valid ${name}`,
                                        ` is not a valid ${name}`,
                                    ),
                                ),
                            ]),
                        ]),
                    ),
                ],
                true,
            ),
        ),

        // Function: containsXxx
        factory.createFunctionDeclaration(
            [factory.createModifier(ts.SyntaxKind.ExportKeyword)],
            undefined,
            factory.createIdentifier(functionNameContainsTyped),
            undefined,
            [
                factory.createParameterDeclaration(
                    undefined,
                    undefined,
                    factory.createIdentifier('value'),
                    undefined,
                    paramType,
                    undefined,
                ),
            ],
            factory.createTypePredicateNode(
                undefined,
                factory.createIdentifier('value'),
                factory.createTypeReferenceNode(factory.createIdentifier(name), undefined),
            ),
            factory.createBlock(
                [
                    factory.createReturnStatement(
                        factory.createCallExpression(
                            factory.createPropertyAccessExpression(
                                factory.createParenthesizedExpression(
                                    factory.createAsExpression(
                                        factory.createIdentifier('ALL'),
                                        factory.createTypeReferenceNode(
                                            factory.createIdentifier('ReadonlySet'),
                                            [paramType],
                                        ),
                                    ),
                                ),
                                factory.createIdentifier('has'),
                            ),
                            undefined,
                            [factory.createIdentifier('value')],
                        ),
                    ),
                ],
                true,
            ),
        ),

        // Function: contains
        factory.createFunctionDeclaration(
            [factory.createModifier(ts.SyntaxKind.ExportKeyword)],
            undefined,
            factory.createIdentifier('contains'),
            undefined,
            [
                factory.createParameterDeclaration(
                    undefined,
                    undefined,
                    factory.createIdentifier('value'),
                    undefined,
                    factory.createKeywordTypeNode(ts.SyntaxKind.UnknownKeyword),
                    undefined,
                ),
            ],
            factory.createTypePredicateNode(
                undefined,
                factory.createIdentifier('value'),
                factory.createTypeReferenceNode(factory.createIdentifier(name), undefined),
            ),
            factory.createBlock(
                [
                    factory.createReturnStatement(
                        factory.createBinaryExpression(
                            factory.createBinaryExpression(
                                factory.createTypeOfExpression(factory.createIdentifier('value')),
                                factory.createToken(ts.SyntaxKind.EqualsEqualsEqualsToken),
                                factory.createStringLiteral(paramTypeLiteral),
                            ),
                            factory.createToken(ts.SyntaxKind.AmpersandAmpersandToken),
                            factory.createCallExpression(
                                factory.createPropertyAccessExpression(
                                    factory.createParenthesizedExpression(
                                        factory.createAsExpression(
                                            factory.createIdentifier('ALL'),
                                            factory.createTypeReferenceNode(
                                                factory.createIdentifier('ReadonlySet'),
                                                [paramType],
                                            ),
                                        ),
                                    ),
                                    factory.createIdentifier('has'),
                                ),
                                undefined,
                                [factory.createIdentifier('value')],
                            ),
                        ),
                    ),
                ],
                true,
            ),
        ),
    ];
}

/**
 * Create the lookup table mapping each enum value to the name of its member, along with the
 * function reading from it.
 *
 * @param {string} name The name of the enum.
 * @param {readonly {identifier: string}[]} members The enum members.
 * @returns {ts.Statement[]} the name lookup table and the associated function.
 */
function createEnumNameFunction(name, members) {
    return [
        factory.createVariableStatement(
            [factory.createModifier(ts.SyntaxKind.ExportKeyword)],
            factory.createVariableDeclarationList(
                [
                    factory.createVariableDeclaration(
                        factory.createIdentifier('NAME_OF'),
                        undefined,
                        undefined,
                        factory.createAsExpression(
                            factory.createObjectLiteralExpression(
                                [
                                    ...members.map((member) =>
                                        factory.createPropertyAssignment(
                                            factory.createComputedPropertyName(
                                                factory.createPropertyAccessExpression(
                                                    factory.createIdentifier(name),
                                                    factory.createIdentifier(member.identifier),
                                                ),
                                            ),
                                            factory.createStringLiteral(member.identifier),
                                        ),
                                    ),
                                ],
                                true,
                            ),
                            factory.createTypeReferenceNode(
                                factory.createIdentifier('const'),
                                undefined,
                            ),
                        ),
                    ),
                ],
                ts.NodeFlags.Const,
            ),
        ),
        factory.createFunctionDeclaration(
            [factory.createModifier(ts.SyntaxKind.ExportKeyword)],
            undefined,
            factory.createIdentifier('nameOf'),
            [
                factory.createTypeParameterDeclaration(
                    undefined,
                    factory.createIdentifier('T'),
                    u53Keyword,
                    undefined,
                ),
            ],
            [
                factory.createParameterDeclaration(
                    undefined,
                    undefined,
                    factory.createIdentifier('value'),
                    undefined,
                    factory.createTypeReferenceNode(factory.createIdentifier('T'), undefined),
                    undefined,
                ),
            ],
            factory.createUnionTypeNode([
                factory.createKeywordTypeNode(ts.SyntaxKind.StringKeyword),
                factory.createKeywordTypeNode(ts.SyntaxKind.UndefinedKeyword),
            ]),
            factory.createBlock(
                [
                    factory.createReturnStatement(
                        factory.createElementAccessExpression(
                            factory.createParenthesizedExpression(
                                factory.createAsExpression(
                                    factory.createIdentifier('NAME_OF'),
                                    factory.createTypeReferenceNode(
                                        factory.createIdentifier('Record'),
                                        [
                                            u53Keyword,
                                            factory.createUnionTypeNode([
                                                factory.createKeywordTypeNode(
                                                    ts.SyntaxKind.StringKeyword,
                                                ),
                                                factory.createKeywordTypeNode(
                                                    ts.SyntaxKind.UndefinedKeyword,
                                                ),
                                            ]),
                                        ],
                                    ),
                                ),
                            ),
                            factory.createIdentifier('value'),
                        ),
                    ),
                ],
                true,
            ),
        ),
    ];
}

/**
 * Create the function instantiating a store that holds a value of the enum.
 *
 * @param {string} name The name of the enum.
 * @returns {ts.Statement} the store factory function.
 */
function createEnumStoreFactoryFunction(name) {
    return factory.createFunctionDeclaration(
        [factory.createModifier(ts.SyntaxKind.ExportKeyword)],
        undefined,
        factory.createIdentifier('createStore'),
        [
            factory.createTypeParameterDeclaration(
                undefined,
                factory.createIdentifier('S'),
                factory.createTypeReferenceNode(factory.createIdentifier('MonotonicEnumStore'), [
                    factory.createTypeReferenceNode(factory.createIdentifier(name), undefined),
                ]),
                undefined,
            ),
        ],
        [
            factory.createParameterDeclaration(
                undefined,
                undefined,
                factory.createIdentifier('constructor'),
                undefined,
                factory.createConstructorTypeNode(
                    undefined,
                    undefined,
                    [
                        factory.createParameterDeclaration(
                            undefined,
                            undefined,
                            factory.createIdentifier('initial'),
                            undefined,
                            factory.createTypeReferenceNode(
                                factory.createIdentifier(name),
                                undefined,
                            ),
                            undefined,
                        ),
                        factory.createParameterDeclaration(
                            undefined,
                            undefined,
                            factory.createIdentifier('activator'),
                            factory.createToken(ts.SyntaxKind.QuestionToken),
                            factory.createKeywordTypeNode(ts.SyntaxKind.UndefinedKeyword),
                            undefined,
                        ),
                        factory.createParameterDeclaration(
                            undefined,
                            undefined,
                            factory.createIdentifier('debug'),
                            factory.createToken(ts.SyntaxKind.QuestionToken),
                            factory.createTypeReferenceNode(
                                factory.createIdentifier('StoreDebug'),
                                [
                                    factory.createTypeReferenceNode(
                                        factory.createIdentifier(name),
                                        undefined,
                                    ),
                                ],
                            ),
                            undefined,
                        ),
                    ],
                    factory.createTypeReferenceNode(factory.createIdentifier('S'), undefined),
                ),
                undefined,
            ),
            factory.createParameterDeclaration(
                undefined,
                undefined,
                factory.createIdentifier('initial'),
                undefined,
                factory.createTypeReferenceNode(factory.createIdentifier(name), undefined),
                undefined,
            ),
            factory.createParameterDeclaration(
                undefined,
                undefined,
                factory.createIdentifier('debug'),
                factory.createToken(ts.SyntaxKind.QuestionToken),
                factory.createTypeLiteralNode([
                    factory.createPropertySignature(
                        undefined,
                        factory.createIdentifier('log'),
                        undefined,
                        factory.createTypeReferenceNode(
                            factory.createIdentifier('Logger'),
                            undefined,
                        ),
                    ),
                    factory.createPropertySignature(
                        undefined,
                        factory.createIdentifier('tag'),
                        undefined,
                        factory.createKeywordTypeNode(ts.SyntaxKind.StringKeyword),
                    ),
                ]),
                undefined,
            ),
        ],
        factory.createTypeReferenceNode(factory.createIdentifier('S'), undefined),
        factory.createBlock(
            [
                factory.createReturnStatement(
                    factory.createNewExpression(
                        factory.createIdentifier('constructor'),
                        undefined,
                        [
                            factory.createIdentifier('initial'),
                            factory.createIdentifier('undefined'),
                            factory.createConditionalExpression(
                                factory.createBinaryExpression(
                                    factory.createIdentifier('debug'),
                                    factory.createToken(ts.SyntaxKind.EqualsEqualsEqualsToken),
                                    factory.createIdentifier('undefined'),
                                ),
                                undefined,
                                factory.createIdentifier('undefined'),
                                undefined,
                                factory.createObjectLiteralExpression(
                                    [
                                        factory.createPropertyAssignment(
                                            factory.createIdentifier('log'),
                                            factory.createPropertyAccessExpression(
                                                factory.createIdentifier('debug'),
                                                factory.createIdentifier('log'),
                                            ),
                                        ),
                                        factory.createPropertyAssignment(
                                            factory.createIdentifier('tag'),
                                            factory.createPropertyAccessExpression(
                                                factory.createIdentifier('debug'),
                                                factory.createIdentifier('tag'),
                                            ),
                                        ),
                                        factory.createPropertyAssignment(
                                            factory.createIdentifier('representation'),
                                            factory.createArrowFunction(
                                                undefined,
                                                undefined,
                                                [
                                                    factory.createParameterDeclaration(
                                                        undefined,
                                                        undefined,
                                                        factory.createIdentifier('name'),
                                                        undefined,
                                                        undefined,
                                                        undefined,
                                                    ),
                                                ],
                                                factory.createKeywordTypeNode(
                                                    ts.SyntaxKind.StringKeyword,
                                                ),
                                                factory.createToken(
                                                    ts.SyntaxKind.EqualsGreaterThanToken,
                                                ),
                                                factory.createElementAccessExpression(
                                                    factory.createIdentifier('NAME_OF'),
                                                    factory.createIdentifier('name'),
                                                ),
                                            ),
                                        ),
                                    ],
                                    true,
                                ),
                            ),
                        ],
                    ),
                ),
            ],
            true,
        ),
    );
}

/**
 * Create the namespace holding the utilities requested for an enum by its `@generate` annotation.
 *
 * @param {string} name The name of the enum.
 * @param {readonly {identifier: string, initializer: ts.Expression}[]} members The enum members.
 * @param {ReadonlySet<string>} utils The requested utility functions.
 * @param {string | undefined} initializerType The kind of initialiser the members use.
 * @returns {ts.Statement} the utils namespace of the enum.
 */
function createEnumUtilsNamespace(name, members, utils, initializerType) {
    /** @type {ts.Statement[]} */
    const nodes = [];

    // Add conversion function and constant set of all enum members (if
    // requested)
    if (utils.has('convert')) {
        nodes.push(...createEnumConversionAndConstantSet(name, members, initializerType));
    }

    // Add enum to name mapper function (if requested)
    if (utils.has('name')) {
        nodes.push(...createEnumNameFunction(name, members));
    }

    // Add enum store factory function (if requested)
    if (utils.has('store')) {
        nodes.push(createEnumStoreFactoryFunction(name));
    }

    // Create utils namespace
    return factory.createModuleDeclaration(
        [factory.createModifier(ts.SyntaxKind.ExportKeyword)],
        factory.createIdentifier(`${name}Utils`),
        factory.createModuleBlock(nodes),
        ts.NodeFlags.Namespace,
    );
}

/**
 * Create the namespace whose constants emulate the members of an enum.
 *
 * @param {string} name The name of the enum.
 * @param {readonly {identifier: string, initializer: ts.Expression, comments: ts.SynthesizedComment[]}[]} members
 *   The enum members.
 * @returns {ts.Statement} the namespace emulating the enum.
 */
function createEnumNamespace(name, members) {
    return factory.createModuleDeclaration(
        [factory.createModifier(ts.SyntaxKind.ExportKeyword)],
        factory.createIdentifier(name),
        factory.createModuleBlock(
            members
                .map((member) => [
                    factory.createVariableStatement(
                        [factory.createModifier(ts.SyntaxKind.ExportKeyword)],
                        factory.createVariableDeclarationList(
                            [
                                factory.createVariableDeclaration(
                                    factory.createIdentifier(member.identifier),
                                    undefined,
                                    undefined,
                                    member.initializer,
                                ),
                            ],
                            ts.NodeFlags.Const,
                        ),
                    ),
                    ts.setSyntheticLeadingComments(
                        factory.createTypeAliasDeclaration(
                            [factory.createModifier(ts.SyntaxKind.ExportKeyword)],
                            factory.createIdentifier(member.identifier),
                            undefined,
                            factory.createTypeQueryNode(
                                factory.createIdentifier(member.identifier),
                            ),
                        ),
                        member.comments,
                    ),
                ])
                .flat(2),
        ),
        ts.NodeFlags.Namespace,
    );
}

/**
 * Extract the members of an enum declaration, along with the kind of initialiser they use.
 *
 * @param {ts.SourceFile} source The schema source file.
 * @param {ts.NodeArray<ts.EnumMember>} members The members of the enum declaration.
 * @returns {[
 *   members: {identifier: string, initializer: ts.Expression, comments: ts.SynthesizedComment[]}[],
 *   initializerType: string | undefined,
 * ]} the members and the kind of initialiser they use.
 * @throws {SchemaError} if a member has an unsupported or inconsistent initialiser.
 */
function getMembers(source, members) {
    let hasInitializers = false;
    const results = [];
    /** @type {Set<string>} */
    const initializerKinds = new Set();
    for (const [index, member] of members.entries()) {
        if (!ts.isIdentifier(member.name)) {
            throw new SchemaError('Enum member name must be an identifier', source, member);
        }
        const identifier = member.name.text;

        // Validate initialiser
        /** @type {ts.Expression | undefined} */
        let initializer;
        if (member.initializer === undefined && hasInitializers) {
            throw new SchemaError(
                'Either all enum members should have initialisers or none of them',
                source,
                member,
            );
        }
        if (member.initializer !== undefined) {
            hasInitializers = true;
            if (ts.isNumericLiteral(member.initializer)) {
                initializer = factory.createNumericLiteral(member.initializer.text);
                initializerKinds.add('number');
            } else if (ts.isStringLiteral(member.initializer)) {
                initializer = factory.createStringLiteral(member.initializer.text);
                initializerKinds.add('string');
            } else {
                throw new SchemaError(
                    'Enum member must have a numeric or string literal as initialiser',
                    source,
                    member,
                );
            }
        }
        const comments = getLeadingComments(member, source);
        results.push({
            identifier,
            initializer: initializer ?? factory.createNumericLiteral(index),
            comments,
        });
    }
    if (initializerKinds.size > 1) {
        throw new SchemaError(
            `Enum members must all have the same initialiser kind, not a mix of [${new Array(
                ...initializerKinds,
            )}]`,
            source,
            members[0] ?? source,
        );
    }
    return [results, initializerKinds.values().next().value];
}

/**
 * Transform an enum declaration into its safe enum equivalent.
 *
 * @param {ts.SourceFile} source The schema source file.
 * @param {ts.EnumDeclaration} declaration The enum declaration to transform.
 * @returns {ts.Statement[]} the statements emulating the enum.
 * @throws {SchemaError} if the enum declaration cannot be transformed.
 */
function createSafeEnumNode(source, declaration) {
    const name = declaration.name.text;
    /** @type {ts.Statement[]} */
    const nodes = [];

    // Get comments of the enum and parse 'generate' annotations (if any) in
    // order to determine which utility functions should be generated.
    const comments = getLeadingComments(declaration, source);
    const utils = new Set(
        [
            ...comments
                .map((comment) => comment.text)
                .join('\n')
                .matchAll(/@generate (?<utils>.+)/gmu),
        ]
            .map(([_, requested]) => (requested ?? '').split(' '))
            .flat(2),
    );

    // Extract each enum member and the associated initialiser
    const [members, initializerType] = getMembers(source, declaration.members);

    // Create the namespace that emulates the enum in a safe manner
    nodes.push(createEnumNamespace(name, members));

    // Create type alias for the namespaced enum
    nodes.push(
        ts.setSyntheticLeadingComments(
            factory.createTypeAliasDeclaration(
                [factory.createModifier(ts.SyntaxKind.ExportKeyword)],
                factory.createIdentifier(name),
                undefined,
                factory.createIndexedAccessTypeNode(
                    factory.createTypeQueryNode(factory.createIdentifier(name)),
                    factory.createTypeOperatorNode(
                        ts.SyntaxKind.KeyOfKeyword,
                        factory.createTypeQueryNode(factory.createIdentifier(name)),
                    ),
                ),
            ),
            comments,
        ),
    );

    // Create utils namespace and functions
    if (utils.size > 0) {
        nodes.push(createEnumUtilsNamespace(name, members, utils, initializerType));
    }

    return nodes;
}

/**
 * Extract the named bindings and the specifier of an import declaration in a schema.
 *
 * Note: The specifier is copied verbatim into the generated module, which does not sit beside the
 * schema. Relative specifiers would therefore resolve from the wrong directory and are rejected.
 *
 * @param {ts.SourceFile} source The schema source file.
 * @param {ts.ImportDeclaration} declaration The import declaration to parse.
 * @returns {SchemaImport} the parsed import declaration.
 * @throws {SchemaError} if the import declaration is not a named import with an absolute specifier.
 */
function parseSchemaImport(source, declaration) {
    if (!ts.isStringLiteral(declaration.moduleSpecifier)) {
        throw new SchemaError('Import specifier must be a string literal', source, declaration);
    }
    const specifier = declaration.moduleSpecifier.text;
    if (specifier.startsWith('.')) {
        throw new SchemaError(
            `Relative import specifier '${specifier}' cannot be used in a schema, because it would resolve from the directory of the generated module. Use a path alias or a bare package specifier instead`,
            source,
            declaration,
        );
    }
    const namedBindings = declaration.importClause?.namedBindings;
    if (namedBindings === undefined || !ts.isNamedImports(namedBindings)) {
        throw new SchemaError(
            'Schema imports must be named imports (e.g. `import type {Foo} from ...`)',
            source,
            declaration,
        );
    }
    return {
        specifier,
        bindings: namedBindings.elements.map((element) => ({
            propertyName: element.propertyName?.text,
            name: element.name.text,
        })),
    };
}

/**
 * Collect the names of all identifiers referenced by the given statements.
 *
 * @param {readonly ts.Node[]} statements The statements to scan.
 * @returns {ReadonlySet<string>} the names of all referenced identifiers.
 */
function collectReferencedIdentifiers(statements) {
    /** @type {Set<string>} */
    const identifiers = new Set();
    /**
     * Collect the name of `node`, if it is an identifier, then descend into its children.
     *
     * @param {ts.Node} node The node to collect identifiers from.
     */
    function visit(node) {
        if (ts.isIdentifier(node)) {
            identifiers.add(node.text);
        }
        ts.forEachChild(node, visit);
    }
    for (const statement of statements) {
        visit(statement);
    }
    return identifiers;
}

/**
 * Create top-level type-only import declarations for all imports whose bindings are referenced by
 * the generated statements.
 *
 * Note: Type-only imports are emitted at the top level (i.e. `import type {Foo} from ...` instead of
 * `import {type Foo} from ...`), so that they are elided completely, even under
 * `verbatimModuleSyntax`.
 *
 * @param {readonly SchemaImport[]} imports The import declarations of the schema.
 * @param {readonly ts.Statement[]} statements The generated statements.
 * @returns {ts.Statement[]} the import declarations to emit.
 */
function createImportDeclarations(imports, statements) {
    const referenced = collectReferencedIdentifiers(statements);
    return imports
        .map(({specifier, bindings}) => ({
            specifier,
            bindings: bindings.filter(({name}) => referenced.has(name)),
        }))
        .filter(({bindings}) => bindings.length > 0)
        .map(({specifier, bindings}) =>
            factory.createImportDeclaration(
                undefined,
                factory.createImportClause(
                    ts.SyntaxKind.TypeKeyword,
                    undefined,
                    factory.createNamedImports(
                        bindings.map(({propertyName, name}) =>
                            factory.createImportSpecifier(
                                false,
                                propertyName === undefined
                                    ? undefined
                                    : factory.createIdentifier(propertyName),
                                factory.createIdentifier(name),
                            ),
                        ),
                    ),
                ),
                factory.createStringLiteral(specifier),
                undefined,
            ),
        );
}

/**
 * Generate the safe enum variants of all enums declared in a schema.
 *
 * The generated module is not formatted. Note that the returned text is generated fully in memory,
 * so a rejected schema cannot leave a partially written module behind.
 *
 * @param {string} schema The source text of the schema.
 * @param {string} [schemaPath] The path of the schema, used in error messages.
 * @returns {string} the source text of the generated module.
 * @throws {SchemaError} if the schema contains a statement that cannot be transformed.
 */
export function generateSafeEnums(schema, schemaPath = 'schema.ts') {
    const [directives, schemaWithoutDirectives] = extractTsDirectives(schema);
    const source = createSource(schemaPath, schemaWithoutDirectives);

    // Generate safe enum types for each enum declaration, and gather the imports to be copied into
    // the generated module.
    /** @type {SchemaImport[]} */
    const imports = [];
    /** @type {ts.Statement[]} */
    const statements = [];
    for (const node of source.statements) {
        switch (node.kind) {
            case ts.SyntaxKind.ImportDeclaration:
                imports.push(parseSchemaImport(source, /** @type {ts.ImportDeclaration} */ (node)));
                break;
            case ts.SyntaxKind.EnumDeclaration:
                statements.push(
                    ...createSafeEnumNode(source, /** @type {ts.EnumDeclaration} */ (node)),
                );
                break;
            default:
                throw new SchemaError(
                    `A schema may only contain import and enum declarations, got ${
                        ts.SyntaxKind[node.kind]
                    }`,
                    source,
                    node,
                );
        }
    }

    // Prepend the imports that the generated statements actually reference
    const output = factory.updateSourceFile(createSource('output.ts', ''), [
        ...createImportDeclarations(imports, statements),
        ...statements,
    ]);

    // Print the generated module, wrapped in a comment indicating that it is generated. Re-insert
    // the TypeScript directives below the warning, where they still precede the first statement and
    // therefore still apply.
    const printer = ts.createPrinter();
    return [
        GENERATED_WARNING_COMMENT,
        ...directives,
        '',
        printer.printFile(output),
        GENERATED_WARNING_COMMENT,
        VIM_MODELINE,
    ].join('\n');
}
